name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOPROXY: "https://proxy.golang.org,direct"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Install dependencies
        run: |
          go mod download

      - name: Generate wire_gen.go
        run: |
          cd pkg/di && go run github.com/google/wire/cmd/wire

      - name: Generate Swagger docs
        run: |
          cd cmd/api && go get -u github.com/swaggo/swag/cmd/swag
          swag init --parseDependency --parseInternal --parseDepth 1 -md ./documentation -o ./docs

#      - name: Lint code
#        run: |
#          go install github.com/golangci/golangci-lint/cmd/golangci-lint
#          golangci-lint run ./...

      - name: Build the Go application
        run: |
          mkdir -p build/bin
          go build -o build/bin/myapp ./cmd/api

#      - name: Run tests
#        run: |
#          go test -v -race ./...

#      - name: Upload code coverage
#        uses: codecov/codecov-action@v2
#        with:
#          flags: unittests
#          required: true
#          fail_ci_if_error: true
